package com.guild.calendar.constant;

public enum LoaClass {
	//전사
	DESTROYER,GUNLANCER,BERSERKER,PALADIN,
	//무도가
	WARDANCER,SCRAPPER,SOULFIST,GLAIVIER,STRIKER,
	//헌터
	DEADEYE,ARTILLERIST,SHARPSHOOTER,MACHINIST,GUNSLINGER,
	//마법사 
	BARD,SUMMONER,ARCANIST,SORCERESS,
	//암살자
	SHADOWHUNTER,DEATHBLADE,REAPER,
	//스페셜리스트
	PAINTER,AEROMANCER
}
